"""add review

Revision ID: 650197e90b8d
Revises: a35cdd8c67b0
Create Date: 2025-07-01 12:53:22.883509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650197e90b8d'
down_revision = 'a35cdd8c67b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('items', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('items', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.drop_column('items', 'title')
    op.drop_table('reviews')
    # ### end Alembic commands ###
